# Generated by Django 2.2 on 2021-01-25 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('Name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=70)),
                ('Difficulty', models.CharField(choices=[('Hard', 'Hard'), ('Medium', 'Medium'), ('Easy', 'Easy')], max_length=50)),
                ('Acceptance', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('Submissions', models.IntegerField(default=0)),
                ('Accepted', models.IntegerField(default=0)),
                ('Likes', models.IntegerField(default=0)),
                ('DisLikes', models.IntegerField(default=0)),
                ('Text', models.TextField()),
                ('Tags', models.ManyToManyField(to='Questions.Tags')),
            ],
        ),
    ]
